AWSTemplateFormatVersion: 2010-09-09
Description: >
  SSM Automation Document run a custom SSM Command Document against a fleet of
  target instances.jo
Parameters:
  AutomationDocumentName:
    Type: String
    Description: Name of created SSM Automation Document
    Default: RunShellScriptAutomation
Resources:
  AutomationDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Name: !Ref AutomationDocumentName
      DocumentType: Automation
      Content:
        description: Run custom Command Document
        schemaVersion: '0.3'
        assumeRole: '{{AutomationAssumeRole}}'
        parameters:
          AutomationAssumeRole:
            type: String
            default: ''
            description: >-
              (Optional) The ARN of the role that allows Automation to perform
              the actions on your behalf.
          InstanceId:
            type: StringList
            description: "(Required) EC2 Instance(s) to run command"
          commands:
            type: StringList
            description: "(Required) Specify a shell script or a command to run."
            minItems: 1
            displayType: textarea
          workingDirectory:
            type: String
            default: ""
            description: "(Optional) The path to the working directory on your instance."
            maxChars: 4096
          executionTimeout:
            type: String
            default: "3600"
            description: "(Optional) The time in seconds for a command to complete before it is considered to have failed. Default is 3600 (1 hour). Maximum is 172800 (48 hours)."
            allowedPattern: "([1-9][0-9]{0,4})|(1[0-6][0-9]{4})|(17[0-1][0-9]{3})|(172[0-7][0-9]{2})|(172800)"
          OutputS3BucketName:
            type: String
            description: Name of Output S3 Bucket
            default: ''
          OutputS3KeyPrefix:
            type: String
            description: Output S3 Key Prefix
            default: ''
        mainSteps:
          - name: RunCommand
            action: 'aws:runCommand'
            inputs:
              DocumentName: AWS-RunShellScript
              InstanceIds:
                - '{{InstanceId}}'
              Parameters:
                commands: '{{commands}}'
                workingDirectory: '{{workingDirectory}}'
                executionTimeout: '{{executionTimeout}}'
              OutputS3BucketName: '{{OutputS3BucketName}}'
              OutputS3KeyPrefix: '{{OutputS3KeyPrefix}}'